/********************************************************************************
** Form generated from reading UI file 'ApPanels.ui'
**
** Created by: Qt User Interface Compiler version 5.12.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_APPANELS_H
#define UI_APPANELS_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ApPanelsClass
{
public:
    QLabel *AP_background;
    QPushButton *GDSU_btn_left_1;
    QPushButton *GDSU_btn_left_2;
    QPushButton *GDSU_btn_left_3;
    QPushButton *GDSU_btn_left_5;
    QPushButton *GDSU_btn_left_6;
    QPushButton *GDSU_btn_left_4;
    QPushButton *GDSU_btn_right_2;
    QPushButton *GDSU_btn_right_3;
    QPushButton *GDSU_btn_right_5;
    QPushButton *GDSU_btn_right_6;
    QPushButton *GDSU_btn_right_1;
    QPushButton *GDSU_btn_right_4;
    QPushButton *GDSU_btn_bottom_1;
    QPushButton *GDSU_btn_bottom_2;
    QPushButton *GDSU_btn_bottom_3;
    QPushButton *GDSU_btn_bottom_4;
    QPushButton *GDSU_btn_bottom_5;
    QPushButton *GDSU_btn_bottom_6;
    QPushButton *GDSU_btn_bottom_7;
    QPushButton *GDSU_btn_minus;
    QPushButton *GDSU_btn_plus;
    QPushButton *GDSU_btn_circle;
    QPushButton *Panel_1_switch_1;
    QPushButton *Panel_1_switch_2;
    QPushButton *Panel_1_switch_3;
    QPushButton *Panel_1_button_1;
    QPushButton *Panel_2_switch_1;
    QPushButton *Panel_2_switch_2;
    QPushButton *Panel_2_switch_3;
    QPushButton *Panel_2_switch_4;
    QLabel *Panel_2_led_1;
    QLabel *Panel_2_led_2;
    QLabel *Panel_2_led_3;
    QLabel *Panel_2_led_4;
    QLabel *Panel_2_led_5;
    QLabel *Panel_2_led_6;
    QLabel *Panel_2_led_7;
    QLabel *Panel_2_led_8;
    QLabel *Panel_2_led_9;
    QLabel *Panel_2_led_10;
    QPushButton *GDSU_switch_1;
    QLabel *Panel_1_led_1;
    QPushButton *Panel_2_button_1;

    void setupUi(QWidget *ApPanelsClass)
    {
        if (ApPanelsClass->objectName().isEmpty())
            ApPanelsClass->setObjectName(QString::fromUtf8("ApPanelsClass"));
        ApPanelsClass->resize(1920, 1080);
        AP_background = new QLabel(ApPanelsClass);
        AP_background->setObjectName(QString::fromUtf8("AP_background"));
        AP_background->setGeometry(QRect(0, 0, 1920, 1080));
        AP_background->setPixmap(QPixmap(QString::fromUtf8(":/prefijoNuevo/Multimedia/GUI/ApPanels.png")));
        GDSU_btn_left_1 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_1->setObjectName(QString::fromUtf8("GDSU_btn_left_1"));
        GDSU_btn_left_1->setEnabled(true);
        GDSU_btn_left_1->setGeometry(QRect(88, 290, 39, 54));
        GDSU_btn_left_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_button_vertical_pressed.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_btn_left_1->setIcon(icon);
        GDSU_btn_left_1->setIconSize(QSize(39, 54));
        GDSU_btn_left_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_left_2 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_2->setObjectName(QString::fromUtf8("GDSU_btn_left_2"));
        GDSU_btn_left_2->setEnabled(true);
        GDSU_btn_left_2->setGeometry(QRect(88, 382, 39, 54));
        GDSU_btn_left_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_left_2->setIcon(icon);
        GDSU_btn_left_2->setIconSize(QSize(39, 54));
        GDSU_btn_left_2->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_left_3 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_3->setObjectName(QString::fromUtf8("GDSU_btn_left_3"));
        GDSU_btn_left_3->setEnabled(true);
        GDSU_btn_left_3->setGeometry(QRect(88, 473, 39, 54));
        GDSU_btn_left_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_left_3->setIcon(icon);
        GDSU_btn_left_3->setIconSize(QSize(39, 54));
        GDSU_btn_left_3->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_left_5 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_5->setObjectName(QString::fromUtf8("GDSU_btn_left_5"));
        GDSU_btn_left_5->setEnabled(true);
        GDSU_btn_left_5->setGeometry(QRect(88, 662, 39, 54));
        GDSU_btn_left_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_left_5->setIcon(icon);
        GDSU_btn_left_5->setIconSize(QSize(39, 54));
        GDSU_btn_left_5->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_left_6 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_6->setObjectName(QString::fromUtf8("GDSU_btn_left_6"));
        GDSU_btn_left_6->setEnabled(true);
        GDSU_btn_left_6->setGeometry(QRect(88, 756, 39, 54));
        GDSU_btn_left_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_left_6->setIcon(icon);
        GDSU_btn_left_6->setIconSize(QSize(39, 54));
        GDSU_btn_left_6->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_left_4 = new QPushButton(ApPanelsClass);
        GDSU_btn_left_4->setObjectName(QString::fromUtf8("GDSU_btn_left_4"));
        GDSU_btn_left_4->setEnabled(true);
        GDSU_btn_left_4->setGeometry(QRect(88, 570, 39, 54));
        GDSU_btn_left_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_left_4->setIcon(icon);
        GDSU_btn_left_4->setIconSize(QSize(39, 54));
        GDSU_btn_left_4->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_2 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_2->setObjectName(QString::fromUtf8("GDSU_btn_right_2"));
        GDSU_btn_right_2->setEnabled(true);
        GDSU_btn_right_2->setGeometry(QRect(1092, 382, 39, 54));
        GDSU_btn_right_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_2->setIcon(icon);
        GDSU_btn_right_2->setIconSize(QSize(39, 54));
        GDSU_btn_right_2->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_3 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_3->setObjectName(QString::fromUtf8("GDSU_btn_right_3"));
        GDSU_btn_right_3->setEnabled(true);
        GDSU_btn_right_3->setGeometry(QRect(1092, 473, 39, 54));
        GDSU_btn_right_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_3->setIcon(icon);
        GDSU_btn_right_3->setIconSize(QSize(39, 54));
        GDSU_btn_right_3->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_5 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_5->setObjectName(QString::fromUtf8("GDSU_btn_right_5"));
        GDSU_btn_right_5->setEnabled(true);
        GDSU_btn_right_5->setGeometry(QRect(1092, 662, 39, 54));
        GDSU_btn_right_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_5->setIcon(icon);
        GDSU_btn_right_5->setIconSize(QSize(39, 54));
        GDSU_btn_right_5->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_6 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_6->setObjectName(QString::fromUtf8("GDSU_btn_right_6"));
        GDSU_btn_right_6->setEnabled(true);
        GDSU_btn_right_6->setGeometry(QRect(1092, 757, 39, 54));
        GDSU_btn_right_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_6->setIcon(icon);
        GDSU_btn_right_6->setIconSize(QSize(39, 54));
        GDSU_btn_right_6->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_1 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_1->setObjectName(QString::fromUtf8("GDSU_btn_right_1"));
        GDSU_btn_right_1->setEnabled(true);
        GDSU_btn_right_1->setGeometry(QRect(1092, 290, 39, 54));
        GDSU_btn_right_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_1->setIcon(icon);
        GDSU_btn_right_1->setIconSize(QSize(39, 54));
        GDSU_btn_right_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_right_4 = new QPushButton(ApPanelsClass);
        GDSU_btn_right_4->setObjectName(QString::fromUtf8("GDSU_btn_right_4"));
        GDSU_btn_right_4->setEnabled(true);
        GDSU_btn_right_4->setGeometry(QRect(1092, 570, 39, 54));
        GDSU_btn_right_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_right_4->setIcon(icon);
        GDSU_btn_right_4->setIconSize(QSize(39, 54));
        GDSU_btn_right_4->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_vertical_pressed.png"))));
        GDSU_btn_bottom_1 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_1->setObjectName(QString::fromUtf8("GDSU_btn_bottom_1"));
        GDSU_btn_bottom_1->setEnabled(true);
        GDSU_btn_bottom_1->setGeometry(QRect(250, 902, 59, 34));
        GDSU_btn_bottom_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_button_horizontal_pressed.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_btn_bottom_1->setIcon(icon1);
        GDSU_btn_bottom_1->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_2 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_2->setObjectName(QString::fromUtf8("GDSU_btn_bottom_2"));
        GDSU_btn_bottom_2->setEnabled(true);
        GDSU_btn_bottom_2->setGeometry(QRect(360, 902, 59, 34));
        GDSU_btn_bottom_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_2->setIcon(icon1);
        GDSU_btn_bottom_2->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_2->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_3 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_3->setObjectName(QString::fromUtf8("GDSU_btn_bottom_3"));
        GDSU_btn_bottom_3->setEnabled(true);
        GDSU_btn_bottom_3->setGeometry(QRect(472, 902, 59, 34));
        GDSU_btn_bottom_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_3->setIcon(icon1);
        GDSU_btn_bottom_3->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_3->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_4 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_4->setObjectName(QString::fromUtf8("GDSU_btn_bottom_4"));
        GDSU_btn_bottom_4->setEnabled(true);
        GDSU_btn_bottom_4->setGeometry(QRect(581, 902, 59, 34));
        GDSU_btn_bottom_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_4->setIcon(icon1);
        GDSU_btn_bottom_4->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_4->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_5 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_5->setObjectName(QString::fromUtf8("GDSU_btn_bottom_5"));
        GDSU_btn_bottom_5->setEnabled(true);
        GDSU_btn_bottom_5->setGeometry(QRect(691, 902, 59, 34));
        GDSU_btn_bottom_5->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_5->setIcon(icon1);
        GDSU_btn_bottom_5->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_5->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_6 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_6->setObjectName(QString::fromUtf8("GDSU_btn_bottom_6"));
        GDSU_btn_bottom_6->setEnabled(true);
        GDSU_btn_bottom_6->setGeometry(QRect(795, 902, 59, 34));
        GDSU_btn_bottom_6->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_6->setIcon(icon1);
        GDSU_btn_bottom_6->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_6->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_bottom_7 = new QPushButton(ApPanelsClass);
        GDSU_btn_bottom_7->setObjectName(QString::fromUtf8("GDSU_btn_bottom_7"));
        GDSU_btn_bottom_7->setEnabled(true);
        GDSU_btn_bottom_7->setGeometry(QRect(905, 902, 59, 34));
        GDSU_btn_bottom_7->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        GDSU_btn_bottom_7->setIcon(icon1);
        GDSU_btn_bottom_7->setIconSize(QSize(59, 34));
        GDSU_btn_bottom_7->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_horizontal_pressed.png"))));
        GDSU_btn_minus = new QPushButton(ApPanelsClass);
        GDSU_btn_minus->setObjectName(QString::fromUtf8("GDSU_btn_minus"));
        GDSU_btn_minus->setEnabled(true);
        GDSU_btn_minus->setGeometry(QRect(80, 902, 53, 36));
        GDSU_btn_minus->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_button_minus_pressed.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_btn_minus->setIcon(icon2);
        GDSU_btn_minus->setIconSize(QSize(53, 36));
        GDSU_btn_minus->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_minus_pressed.png"))));
        GDSU_btn_plus = new QPushButton(ApPanelsClass);
        GDSU_btn_plus->setObjectName(QString::fromUtf8("GDSU_btn_plus"));
        GDSU_btn_plus->setEnabled(true);
        GDSU_btn_plus->setGeometry(QRect(144, 902, 53, 36));
        GDSU_btn_plus->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_button_plus_pressed.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_btn_plus->setIcon(icon3);
        GDSU_btn_plus->setIconSize(QSize(53, 36));
        GDSU_btn_plus->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_plus_pressed.png"))));
        GDSU_btn_circle = new QPushButton(ApPanelsClass);
        GDSU_btn_circle->setObjectName(QString::fromUtf8("GDSU_btn_circle"));
        GDSU_btn_circle->setEnabled(true);
        GDSU_btn_circle->setGeometry(QRect(1001, 901, 40, 38));
        GDSU_btn_circle->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_button_circle_pressed.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_btn_circle->setIcon(icon4);
        GDSU_btn_circle->setIconSize(QSize(40, 38));
        GDSU_btn_circle->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/GDSU_button_circle_pressed.png"))));
        Panel_1_switch_1 = new QPushButton(ApPanelsClass);
        Panel_1_switch_1->setObjectName(QString::fromUtf8("Panel_1_switch_1"));
        Panel_1_switch_1->setEnabled(true);
        Panel_1_switch_1->setGeometry(QRect(1300, 348, 75, 74));
        Panel_1_switch_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_1_switch_1->setIconSize(QSize(75, 74));
        Panel_1_switch_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel1_switch1_1.png"))));
        Panel_1_switch_2 = new QPushButton(ApPanelsClass);
        Panel_1_switch_2->setObjectName(QString::fromUtf8("Panel_1_switch_2"));
        Panel_1_switch_2->setEnabled(true);
        Panel_1_switch_2->setGeometry(QRect(1329, 427, 68, 71));
        Panel_1_switch_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_1_switch_2->setIconSize(QSize(68, 71));
        Panel_1_switch_2->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel1_switch2_1.png"))));
        Panel_1_switch_3 = new QPushButton(ApPanelsClass);
        Panel_1_switch_3->setObjectName(QString::fromUtf8("Panel_1_switch_3"));
        Panel_1_switch_3->setEnabled(true);
        Panel_1_switch_3->setGeometry(QRect(1307, 509, 68, 71));
        Panel_1_switch_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_1_switch_3->setIconSize(QSize(68, 71));
        Panel_1_switch_3->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel1_switch3_1.png"))));
        Panel_1_button_1 = new QPushButton(ApPanelsClass);
        Panel_1_button_1->setObjectName(QString::fromUtf8("Panel_1_button_1"));
        Panel_1_button_1->setEnabled(true);
        Panel_1_button_1->setGeometry(QRect(1369, 525, 76, 66));
        Panel_1_button_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_1_button_1->setIconSize(QSize(76, 66));
        Panel_1_button_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel1_red.png"))));
        Panel_2_switch_1 = new QPushButton(ApPanelsClass);
        Panel_2_switch_1->setObjectName(QString::fromUtf8("Panel_2_switch_1"));
        Panel_2_switch_1->setEnabled(true);
        Panel_2_switch_1->setGeometry(QRect(1236, 820, 85, 67));
        Panel_2_switch_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_2_switch_1->setIconSize(QSize(85, 67));
        Panel_2_switch_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_switch1_1.png"))));
        Panel_2_switch_2 = new QPushButton(ApPanelsClass);
        Panel_2_switch_2->setObjectName(QString::fromUtf8("Panel_2_switch_2"));
        Panel_2_switch_2->setEnabled(true);
        Panel_2_switch_2->setGeometry(QRect(1513, 831, 86, 88));
        Panel_2_switch_2->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_2_switch_2->setIconSize(QSize(86, 88));
        Panel_2_switch_2->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_switch2_1.png"))));
        Panel_2_switch_3 = new QPushButton(ApPanelsClass);
        Panel_2_switch_3->setObjectName(QString::fromUtf8("Panel_2_switch_3"));
        Panel_2_switch_3->setEnabled(true);
        Panel_2_switch_3->setGeometry(QRect(1642, 840, 86, 88));
        Panel_2_switch_3->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_2_switch_3->setIconSize(QSize(86, 88));
        Panel_2_switch_3->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_switch3_1.png"))));
        Panel_2_switch_4 = new QPushButton(ApPanelsClass);
        Panel_2_switch_4->setObjectName(QString::fromUtf8("Panel_2_switch_4"));
        Panel_2_switch_4->setEnabled(true);
        Panel_2_switch_4->setGeometry(QRect(1770, 850, 86, 88));
        Panel_2_switch_4->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        Panel_2_switch_4->setIconSize(QSize(86, 88));
        Panel_2_switch_4->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_switch4_1.png"))));
        Panel_2_led_1 = new QLabel(ApPanelsClass);
        Panel_2_led_1->setObjectName(QString::fromUtf8("Panel_2_led_1"));
        Panel_2_led_1->setEnabled(true);
        Panel_2_led_1->setGeometry(QRect(1254, 658, 64, 62));
        Panel_2_led_1->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led1.png")));
        Panel_2_led_2 = new QLabel(ApPanelsClass);
        Panel_2_led_2->setObjectName(QString::fromUtf8("Panel_2_led_2"));
        Panel_2_led_2->setEnabled(true);
        Panel_2_led_2->setGeometry(QRect(1211, 734, 64, 62));
        Panel_2_led_2->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led2.png")));
        Panel_2_led_3 = new QLabel(ApPanelsClass);
        Panel_2_led_3->setObjectName(QString::fromUtf8("Panel_2_led_3"));
        Panel_2_led_3->setEnabled(true);
        Panel_2_led_3->setGeometry(QRect(1294, 738, 64, 62));
        Panel_2_led_3->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led3.png")));
        Panel_2_led_4 = new QLabel(ApPanelsClass);
        Panel_2_led_4->setObjectName(QString::fromUtf8("Panel_2_led_4"));
        Panel_2_led_4->setEnabled(true);
        Panel_2_led_4->setGeometry(QRect(1398, 663, 64, 62));
        Panel_2_led_4->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led4.png")));
        Panel_2_led_5 = new QLabel(ApPanelsClass);
        Panel_2_led_5->setObjectName(QString::fromUtf8("Panel_2_led_5"));
        Panel_2_led_5->setEnabled(true);
        Panel_2_led_5->setGeometry(QRect(1398, 743, 64, 62));
        Panel_2_led_5->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led5.png")));
        Panel_2_led_6 = new QLabel(ApPanelsClass);
        Panel_2_led_6->setObjectName(QString::fromUtf8("Panel_2_led_6"));
        Panel_2_led_6->setEnabled(true);
        Panel_2_led_6->setGeometry(QRect(1507, 667, 64, 62));
        Panel_2_led_6->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led6.png")));
        Panel_2_led_7 = new QLabel(ApPanelsClass);
        Panel_2_led_7->setObjectName(QString::fromUtf8("Panel_2_led_7"));
        Panel_2_led_7->setEnabled(true);
        Panel_2_led_7->setGeometry(QRect(1573, 669, 64, 62));
        Panel_2_led_7->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led7.png")));
        Panel_2_led_8 = new QLabel(ApPanelsClass);
        Panel_2_led_8->setObjectName(QString::fromUtf8("Panel_2_led_8"));
        Panel_2_led_8->setEnabled(true);
        Panel_2_led_8->setGeometry(QRect(1640, 671, 64, 62));
        Panel_2_led_8->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led8.png")));
        Panel_2_led_9 = new QLabel(ApPanelsClass);
        Panel_2_led_9->setObjectName(QString::fromUtf8("Panel_2_led_9"));
        Panel_2_led_9->setEnabled(true);
        Panel_2_led_9->setGeometry(QRect(1710, 674, 64, 62));
        Panel_2_led_9->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led9.png")));
        Panel_2_led_10 = new QLabel(ApPanelsClass);
        Panel_2_led_10->setObjectName(QString::fromUtf8("Panel_2_led_10"));
        Panel_2_led_10->setEnabled(true);
        Panel_2_led_10->setGeometry(QRect(1781, 676, 64, 62));
        Panel_2_led_10->setPixmap(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_led10.png")));
        GDSU_switch_1 = new QPushButton(ApPanelsClass);
        GDSU_switch_1->setObjectName(QString::fromUtf8("GDSU_switch_1"));
        GDSU_switch_1->setEnabled(true);
        GDSU_switch_1->setGeometry(QRect(0, 204, 57, 103));
        GDSU_switch_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_GDSU_switch1_1.png"), QSize(), QIcon::Normal, QIcon::Off);
        GDSU_switch_1->setIcon(icon5);
        GDSU_switch_1->setIconSize(QSize(57, 103));
        GDSU_switch_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel2_switch1_1.png"))));
        Panel_1_led_1 = new QLabel(ApPanelsClass);
        Panel_1_led_1->setObjectName(QString::fromUtf8("Panel_1_led_1"));
        Panel_1_led_1->setEnabled(true);
        Panel_1_led_1->setGeometry(QRect(1386, 347, 55, 57));
        Panel_1_led_1->setPixmap(QPixmap(QString::fromUtf8(":/prefijoNuevo/Multimedia/GUI/AP_panel1_led1.png")));
        Panel_2_button_1 = new QPushButton(ApPanelsClass);
        Panel_2_button_1->setObjectName(QString::fromUtf8("Panel_2_button_1"));
        Panel_2_button_1->setEnabled(true);
        Panel_2_button_1->setGeometry(QRect(1383, 826, 95, 91));
        Panel_2_button_1->setStyleSheet(QString::fromUtf8("background-color: rgba(255, 255, 255, 0)"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/prefijoNuevo/Multimedia/GUI/AP_panel2_button1.png"), QSize(), QIcon::Normal, QIcon::Off);
        Panel_2_button_1->setIcon(icon6);
        Panel_2_button_1->setIconSize(QSize(95, 91));
        Panel_2_button_1->setProperty("pixmap", QVariant(QPixmap(QString::fromUtf8(":/ApPanels/Multimedia/GUI/AP_panel1_red.png"))));

        retranslateUi(ApPanelsClass);

        QMetaObject::connectSlotsByName(ApPanelsClass);
    } // setupUi

    void retranslateUi(QWidget *ApPanelsClass)
    {
        ApPanelsClass->setWindowTitle(QApplication::translate("ApPanelsClass", "ApPanels", nullptr));
        AP_background->setText(QString());
        GDSU_btn_left_1->setText(QString());
        GDSU_btn_left_2->setText(QString());
        GDSU_btn_left_3->setText(QString());
        GDSU_btn_left_5->setText(QString());
        GDSU_btn_left_6->setText(QString());
        GDSU_btn_left_4->setText(QString());
        GDSU_btn_right_2->setText(QString());
        GDSU_btn_right_3->setText(QString());
        GDSU_btn_right_5->setText(QString());
        GDSU_btn_right_6->setText(QString());
        GDSU_btn_right_1->setText(QString());
        GDSU_btn_right_4->setText(QString());
        GDSU_btn_bottom_1->setText(QString());
        GDSU_btn_bottom_2->setText(QString());
        GDSU_btn_bottom_3->setText(QString());
        GDSU_btn_bottom_4->setText(QString());
        GDSU_btn_bottom_5->setText(QString());
        GDSU_btn_bottom_6->setText(QString());
        GDSU_btn_bottom_7->setText(QString());
        GDSU_btn_minus->setText(QString());
        GDSU_btn_plus->setText(QString());
        GDSU_btn_circle->setText(QString());
        Panel_1_switch_1->setText(QString());
        Panel_1_switch_2->setText(QString());
        Panel_1_switch_3->setText(QString());
        Panel_1_button_1->setText(QString());
        Panel_2_switch_1->setText(QString());
        Panel_2_switch_2->setText(QString());
        Panel_2_switch_3->setText(QString());
        Panel_2_switch_4->setText(QString());
        Panel_2_led_1->setText(QString());
        Panel_2_led_2->setText(QString());
        Panel_2_led_3->setText(QString());
        Panel_2_led_4->setText(QString());
        Panel_2_led_5->setText(QString());
        Panel_2_led_6->setText(QString());
        Panel_2_led_7->setText(QString());
        Panel_2_led_8->setText(QString());
        Panel_2_led_9->setText(QString());
        Panel_2_led_10->setText(QString());
        GDSU_switch_1->setText(QString());
        Panel_1_led_1->setText(QString());
        Panel_2_button_1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class ApPanelsClass: public Ui_ApPanelsClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_APPANELS_H
