#pragma once

enum ELEM_ID
{
	GDSU_BUTTON_LEFT_1,
	GDSU_BUTTON_LEFT_2,
	GDSU_BUTTON_LEFT_3,
	GDSU_BUTTON_LEFT_4,
	GDSU_BUTTON_LEFT_5,
	GDSU_BUTTON_LEFT_6,
	GDSU_BUTTON_RIGHT_1,
	GDSU_BUTTON_RIGHT_2,
	GDSU_BUTTON_RIGHT_3,
	GDSU_BUTTON_RIGHT_4,
	GDSU_BUTTON_RIGHT_5,
	GDSU_BUTTON_RIGHT_6,
	GDSU_BUTTON_BOTTOM_1,
	GDSU_BUTTON_BOTTOM_2,
	GDSU_BUTTON_BOTTOM_3,
	GDSU_BUTTON_BOTTOM_4,
	GDSU_BUTTON_BOTTOM_5,
	GDSU_BUTTON_BOTTOM_6,
	GDSU_BUTTON_BOTTOM_7,
	GDSU_BUTTON_MINUS,
	GDSU_BUTTON_PLUS,
	GDSU_BUTTON_CIRCLE,

	AP_P1_SWITCH_1,
	AP_P1_SWITCH_2,
	AP_P1_SWITCH_3,
	AP_P1_BUTTON,

	AP_P2_SWITCH_1,
	AP_P2_SWITCH_2,
	AP_P2_SWITCH_3,
	AP_P2_SWITCH_4,
	AP_P2_LED_1,
	AP_P2_LED_2,
	AP_P2_LED_3,
	AP_P2_LED_4,
	AP_P2_LED_5,
	AP_P2_LED_6,
	AP_P2_LED_7,
	AP_P2_LED_8,
	AP_P2_LED_9,
	AP_P2_LED_10,

	JTAN_P1_SWITCH_1,
	JTAN_P1_SWITCH_2,
	JTAN_P1_LED_1,
	JTAN_P1_KNOB,

	INVALID_ID
};

enum BUTTON_STATE
{
	RELEASED,
	PRESSED,
	INVALID_BUTTON
};

enum SWITCH_STATE
{
	POS_1,
	POS_2,
	POS_3,
	INVALID_SWITCH
};

enum LED_STATE
{
	OFF,
	ON,
	INVALID_LED
};